openapi: 3.0.2
info:
  title: OpenAPI Course
  description: Specification for OpenAPI Course
  termsOfService: http://example.com/terms/
  contact:
    name: John Thompson
    url: https://springframework.guru
    email: john@springframework.guru
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: "1.0"
servers:
- url: https://dev.example.com
  description: Development Server
- url: https://qa.example.com
  description: QA Server
- url: https://prod.example.com
  description: Production Server
paths:
  /v1/customers:
    get:
      responses:
        200:
          description: List of Customers
          content:
            application/json:
              schema:
                maxItems: 100
                minItems: 1
                type: array
                description: List of Customers
                items:
                  $ref: '#/components/schemas/costumer_inline_response_200'
  /v1/beers:
    get:
      responses:
        200:
          description: List of Beers
          content:
            application/json:
              schema:
                maxItems: 100
                minItems: 1
                type: array
                description: List of Beers
                items:
                  $ref: '#/components/schemas/beer_inline_response_200'
        404:
          description: No Beers Found
components:
  schemas:
    v1customers_address:
      type: object
      properties:
        line1:
          type: string
          example: 123 main
        city:
          type: string
          example: St Pete
        stateCode:
          maxLength: 2
          minLength: 2
          type: string
          description: 2 Letter State Code
          # enum: [AL, AK, AZ, AR, CA]
          enum:
          - AL
          - AK
          - AZ
          - AR
          - CA
        zipCode:
          type: string
          example: "33701"
    costumer_inline_response_200:
      type: object
      properties:
        id:
          type: string
          format: uuid
        firstName:
          maxLength: 100
          minLength: 2
          type: string
          example: John
        lastName:
          maxLength: 100
          minLength: 2
          type: string
          example: Thompson
        address:
          $ref: '#/components/schemas/v1customers_address'
      description: customer object
    v1beer_brewery:
      type: object
      properties:
        name:
          type: string
          example: New brewery
        location:
          type: string
          example: Carlifornia
    beer_inline_response_200:
      type: object
      properties:
        name:
          maxLength: 100
          minLength: 2
          type: string
        style:
          enum:
            - ALE
            - PALE_ALE
            - IPA
            - WHEAT
            - LAGER
          type: string
          description: Beer style
        upc:
          maxLength: 100
          minLength: 2
          type: string
          example: Thompson
        price:
          type: number
          format: float
          example: 30.9
        quantity: 
          type: integer
          format: int32
          example: 120
        brewery:
          $ref: '#/components/schemas/v1beer_brewery'
      description: beer object
